### ISSUE TITLE
handle images properly

### ISSUE THREAD

**Issue by mruwnik** [StampyAI/GDocsRelatedThings#24]
google doesn't allow linking to images?

**Comment by tayler6000** [comment]
This was mentioned in the Big Picture Q&A call, @ChrisRimmer seems to have a work around for this.

**Comment by markovial** [comment]
They seem to be working. [This answer](https://aisafety.info?state=8HIA_) on feature visualization is rendering it properly at least for me.

**Comment by plexish** [comment]
@ChrisRimmer is this complete?

**Comment by ChrisRimmer** [comment]
Images seem to accidentally work. I haven't changed anything and we're still just using the image URLs as provided by the Google Docs API. But they seem to have updated their access control / URL expiry policies or something? I would like to look around more answers but this seems like it's just magically fixed itself?

**Comment by mruwnik** [comment]
some do, some don't - in https://aisafety.info/?state=0_6953r6201r the star image thingy doesn't work

**Comment by ChrisRimmer** [comment]
> some do, some don't - in https://aisafety.info/?state=0_6953r6201r the star image thingy doesn't work

This one should work next time the parser runs over it. The issue there is the image title not having quotes around it in the Markdown, which is fixed in the PR we recently closed.

**Comment by mruwnik** [comment]
The cloudflare hosting seems to work - or at least there have been no complaints since it was added. There are currently < 300 images hosted, so the cleanup script also seems to be working
