### ISSUE TITLE
Alternative Phrasings autogen on new doc creation

### ISSUE THREAD

**Issue by markovial** [StampyAI/GDocsRelatedThings#40]
The current system auto-generates a related section whenever a new doc is created, can we make it so that the alternative phrasings sections also appears automagically on new doc creation?

**Comment by plexish** [comment]
Yes, there is an answer template doc, editing that affects all new docs: https://docs.google.com/document/d/1T-wirrl6HEq13XFTs7DBsUy0OXKaO3htJozZFXdAIAg/edit

Feel free to make the change @markovial

**Comment by mruwnik** [comment]
I added a basic section, but as plex says, feel free to update it
