### ISSUE TITLE
Inline comments in gdocs

### ISSUE THREAD

**Issue by mruwnik** [StampyAI/GDocsRelatedThings#6]
It would be nice for editors to be able to add inline comments to gdocs which would be removed by the parser. 

For example @nosts used greyed out headings to mark sections while writing [this](https://docs.google.com/document/d/1dLxXPwrawz98ycwSA1DSNmPTQZWw5mitFKKBR4Sm9Ek/edit). This works well enough during editing, but can be confusing for reviewers.

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/3942390/220356942-cddaec61-6b5f-4bbd-b64f-001daccdf3f9.png">

**Comment by plexish** [comment]
I think asking people to use comments or suggestions for this might be the cleanest? or if the parser can pick up gray text that would also work

**Comment by Aprillion** [comment]
idea from dev call: whole paragraph starting with `// this is comment` can be removed

**Comment by ChrisRimmer** [comment]
Current proposed implenentation: Any text which is colored in a light grey should just be ignored by the parser

**Comment by mruwnik** [comment]
There are three different versions of light grey in gdocs - light grey 1,2,3. Which one will the parser ignore?
Anything under light grey 1 becomes too hard to read, so i suggest that one.

**Comment by Aprillion** [comment]
colors are not preserves, so why not all
