### ISSUE TITLE
Improve debugging

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/GDocsRelatedThings#68]
When attempting to debug stuff in GDocsRelatedThings, I have a debugging branch that basically logs everything, which is quite an ugly solution.

I'm wondering how we can make this project more amenable to debugging, ideally allowing to edit the code that does parsing and then check the result in a localhost website as we do for stampy-ui.

I'm ok writing this debugging code, I just need some direction on the best way to proceed.

**Comment by jrhender** [comment]
@LeMurphant thanks for this issue. 

> I'm wondering how we can make this project more amenable to debugging, ideally allowing to edit the code that does parsing and then check the result in a localhost website as we do for stampy-ui.

I started a branch with an example server: https://github.com/StampyAI/GDocsRelatedThings/pull/70

But I noticed the `devtool.js` CLI script as well that is in the repo, so that could be an option as well.

**Comment by LeMurphant** [comment]
Thanks @jrhender I had not noticed devtool.js before. This script and your diff script this should address most of my needs. If I have a specific need in the future I will open a new issue.
