### ISSUE TITLE
Split docs into live folder and everything else folder

### ISSUE THREAD

**Issue by mruwnik** [StampyAI/GDocsRelatedThings#7]
To make handling permissions easier, there should be 2 folders:
* Live on site - containing only questions that are live on site. Changing a docs status to/from `Live on site` should move the document to/from this folder
* everything else

The idea being more granular permissions - currently there is no good way to grant someone general editor permissions without them having write access to all the documents

**Comment by mruwnik** [comment]
@ChrisRimmer
Where do you think this should live?
* I originally thought about adding a Coda button, but changing status is to be done via the discord bot, so that would be an extra place to implent this
* the Discord bot seems like the correct place, but what if someone manually changes the status?
* the parser would solve the above problem, at the cost of adding latency

There is also the issue of API keys etc. - whatever calls google would need to have a key somewhere? 

@plex seeing as there will probably have to be some kind of script copying things around, would you like more folders for more granularity?

**Comment by plexish** [comment]
hm, I don't have a strong need for more granular folders, but it might be slightly useful, so if it's cheap we could bucket by status. Slight worry that Google will get annoyed at the extra syncs, but hopefully fine? We have one spare account again now so it's not the end of the world if we have to revert.
