### ISSUE TITLE
Rogue Related section

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/GDocsRelatedThings#9]
There is a non-deleted `Related` section in <https://aisafety.info/?state=6986_> - please check if it just needs to re-run the ingestion with current code or what could be the problem.
![image](https://user-images.githubusercontent.com/1087670/221423635-33e77ac5-c0b2-48d4-b95f-d839e4aa382e.png)

**Comment by mruwnik** [comment]
There was a problem with how gdocs formatted the "Related" in the document - fixing the document causes this to be properly parsed
